from pathlib import Path

root = Path(__file__).resolve().parents[1]
path = root / "scanner.py"
text = path.read_text(encoding="utf-8")
old = '''def run_parallel_indicator_scan(\n    ticker_infos: list[TickerInfo], data_source: str = "tickflow"\n) -> list[ScanResult]:\n    data_source = normalize_data_source(data_source)\n    results: list[ScanResult] = []\n    with ThreadPoolExecutor(max_workers=SCAN_THREADS) as executor:\n        future_to_ticker = {\n            executor.submit(_analyse_one_ticker, ti, data_source): ti\n            for ti in ticker_infos\n        }\n        for future in as_completed(future_to_ticker):\n            ti = future_to_ticker[future]\n            try:\n                results.append(future.result())\n            except Exception as exc:\n                logger.exception("Analysis error for %s", ti.ticker)\n                results.append(\n                    ScanResult(ticker=ti.ticker, name=ti.name, error=str(exc))\n                )\n    results.sort(key=lambda result: result.score.total, reverse=True)\n    return results\n'''
new = '''def run_parallel_indicator_scan(\n    ticker_infos: list[TickerInfo],\n    data_source: str = "tickflow",\n    max_workers: int = SCAN_THREADS,\n) -> list[ScanResult]:\n    data_source = normalize_data_source(data_source)\n    results: list[ScanResult] = []\n    worker_count = max(1, int(max_workers))\n    with ThreadPoolExecutor(max_workers=worker_count) as executor:\n        future_to_ticker = {\n            executor.submit(_analyse_one_ticker, ti, data_source): ti\n            for ti in ticker_infos\n        }\n        with tqdm(\n            total=len(future_to_ticker),\n            desc="Parallel scan",\n            unit="ticker",\n            disable=not sys.stderr.isatty(),\n        ) as progress:\n            for future in as_completed(future_to_ticker):\n                ti = future_to_ticker[future]\n                try:\n                    results.append(future.result())\n                except Exception as exc:\n                    logger.exception("Analysis error for %s", ti.ticker)\n                    results.append(\n                        ScanResult(ticker=ti.ticker, name=ti.name, error=str(exc))\n                    )\n                progress.update(1)\n    results.sort(key=lambda result: result.score.total, reverse=True)\n    return results\n'''
if old not in text:
    raise RuntimeError("parallel scan block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
(root / "tools/patch_parallel_scan.py").unlink(missing_ok=True)
(root / ".github/workflows/patch-parallel-scan.yml").unlink(missing_ok=True)
