from pathlib import Path

path = Path(__file__).with_name("model_v18_migrate.py")
text = path.read_text(encoding="utf-8")
old = '''replace_once(\n    "scanner.py",\n    \'\'\'                        backtest_engine=str(\\n                            row.get("BacktestEngine", "") or ""\\n                        ),\\n\'\'\',\n    \'\'\'                        backtest_engine=str(\\n                            row.get("BacktestEngine", "") or ""\\n                        ),\\n                        backtest_status=str(row.get("BacktestStatus", "") or ""),\\n                        global_calibration_score=_parse_float(row.get("GlobalCalibrationScore", np.nan)),\\n                        global_calibration_confidence=_parse_float(row.get("GlobalCalibrationConfidence", 0.0), 0.0),\\n                        global_calibration_level=str(row.get("GlobalCalibrationLevel", "none") or "none"),\\n\'\'\',\n)\n'''
new = '''replace_once(\n    "scanner.py",\n    \'\'\'                        backtest_return_std_20d=_parse_float(\\n                            row.get("BacktestReturnStd20D", np.nan)\\n                        ),\\n                        composite_score=_parse_float(\\n                            row.get("CompositeScore", np.nan)\\n                        ),\\n\'\'\',\n    \'\'\'                        backtest_return_std_20d=_parse_float(\\n                            row.get("BacktestReturnStd20D", np.nan)\\n                        ),\\n                        backtest_mode=str(row.get("BacktestMode", "") or ""),\\n                        backtest_cache_hit=_parse_bool(row.get("BacktestCacheHit", False)),\\n                        backtest_last_evaluated_date=str(row.get("BacktestLastEvaluatedDate", "") or ""),\\n                        backtest_engine=str(row.get("BacktestEngine", "") or ""),\\n                        backtest_status=str(row.get("BacktestStatus", "") or ""),\\n                        global_calibration_score=_parse_float(row.get("GlobalCalibrationScore", np.nan)),\\n                        global_calibration_confidence=_parse_float(row.get("GlobalCalibrationConfidence", 0.0), 0.0),\\n                        global_calibration_level=str(row.get("GlobalCalibrationLevel", "none") or "none"),\\n                        composite_score=_parse_float(\\n                            row.get("CompositeScore", np.nan)\\n                        ),\\n\'\'\',\n)\n'''
if old not in text:
    raise RuntimeError("target migration block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("prepared model v18 migration")
