from pathlib import Path

path = Path(__file__).with_name("model_v18_migrate.py")
text = path.read_text(encoding="utf-8")


def swap(old: str, new: str, label: str) -> None:
    global text
    if old not in text:
        raise RuntimeError(f"target migration block not found: {label}")
    text = text.replace(old, new, 1)


old_backtest = '''replace_once(\n    "scanner.py",\n    \'\'\'                        backtest_engine=str(\\n                            row.get("BacktestEngine", "") or ""\\n                        ),\\n\'\'\',\n    \'\'\'                        backtest_engine=str(\\n                            row.get("BacktestEngine", "") or ""\\n                        ),\\n                        backtest_status=str(row.get("BacktestStatus", "") or ""),\\n                        global_calibration_score=_parse_float(row.get("GlobalCalibrationScore", np.nan)),\\n                        global_calibration_confidence=_parse_float(row.get("GlobalCalibrationConfidence", 0.0), 0.0),\\n                        global_calibration_level=str(row.get("GlobalCalibrationLevel", "none") or "none"),\\n\'\'\',\n)\n'''
new_backtest = '''replace_once(\n    "scanner.py",\n    \'\'\'                        backtest_return_std_20d=_parse_float(\\n                            row.get("BacktestReturnStd20D", np.nan)\\n                        ),\\n                        composite_score=_parse_float(\\n                            row.get("CompositeScore", np.nan)\\n                        ),\\n\'\'\',\n    \'\'\'                        backtest_return_std_20d=_parse_float(\\n                            row.get("BacktestReturnStd20D", np.nan)\\n                        ),\\n                        backtest_mode=str(row.get("BacktestMode", "") or ""),\\n                        backtest_cache_hit=_parse_bool(row.get("BacktestCacheHit", False)),\\n                        backtest_last_evaluated_date=str(row.get("BacktestLastEvaluatedDate", "") or ""),\\n                        backtest_engine=str(row.get("BacktestEngine", "") or ""),\\n                        backtest_status=str(row.get("BacktestStatus", "") or ""),\\n                        global_calibration_score=_parse_float(row.get("GlobalCalibrationScore", np.nan)),\\n                        global_calibration_confidence=_parse_float(row.get("GlobalCalibrationConfidence", 0.0), 0.0),\\n                        global_calibration_level=str(row.get("GlobalCalibrationLevel", "none") or "none"),\\n                        composite_score=_parse_float(\\n                            row.get("CompositeScore", np.nan)\\n                        ),\\n\'\'\',\n)\n'''
swap(old_backtest, new_backtest, "backtest provenance restore")

old_ranking = '''replace_once(\n    "scanner.py",\n    \'\'\'                        ranking_reason=str(row.get("RankingReason", "") or ""),\\n                        institutional_percentile=_parse_float(\\n\'\'\',\n    \'\'\'                        ranking_reason=str(row.get("RankingReason", "") or ""),\\n                        decision_state=str(row.get("DecisionState", "OBSERVE") or "OBSERVE"),\\n                        decision_reason=str(row.get("DecisionReason", "") or ""),\\n                        trade_readiness=str(row.get("TradeReadiness", row.get("RankingEligibility", "观察")) or "观察"),\\n                        research_tier=str(row.get("ResearchTier", "") or ""),\\n                        model_classification=str(row.get("ModelClassification", row.get("Industry", row.get("Sector", ""))) or ""),\\n                        institutional_percentile=_parse_float(\\n\'\'\',\n)\n'''
new_ranking = '''replace_once(\n    "scanner.py",\n    \'\'\'                        ranking_reason=str(\\n                            row.get("RankingReason", "") or ""\\n                        ),\\n                        institutional_percentile=_parse_float(\\n\'\'\',\n    \'\'\'                        ranking_reason=str(\\n                            row.get("RankingReason", "") or ""\\n                        ),\\n                        decision_state=str(row.get("DecisionState", "OBSERVE") or "OBSERVE"),\\n                        decision_reason=str(row.get("DecisionReason", "") or ""),\\n                        trade_readiness=str(row.get("TradeReadiness", row.get("RankingEligibility", "观察")) or "观察"),\\n                        research_tier=str(row.get("ResearchTier", "") or ""),\\n                        model_classification=str(row.get("ModelClassification", row.get("Industry", row.get("Sector", ""))) or ""),\\n                        institutional_percentile=_parse_float(\\n\'\'\',\n)\n'''
swap(old_ranking, new_ranking, "ranking decision restore")

path.write_text(text, encoding="utf-8")
print("prepared model v18 migration")
